### ISSUE TITLE
Require inside a class is not necessary with autoload composer

### ISSUE THREAD

**Issue by giuseppemorelli** [ittweb/accelasearch-product-mapper#5]
https://github.com/ittweb/accelasearch-product-mapper/blob/d993bb7f41f74760ff92f94a32752802f72fc5ac/src/ProductsMapper.php#L9

Class is "automatically" loaded via PSR-4 on your composer.
You can remove :)

**Comment by marco-zanella** [comment]
Fixed in [https://github.com/ittweb/accelasearch-product-mapper/tree/v1.1](v1.1).
